services:
  - type: web
    name: praticaok-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 60
    envVars:
      - key: AIRTABLE_TOKEN
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: META_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
